baseURL = "https://hyacinth.satellites.ac.cn/"
languageCode = "zh-CN"
title = "风信子卫星 | HyacinthSat"
theme = "noteworthy"
enableRobotsTXT = true
summaryLength = 10

[pagination]
  pagerSize = 4

googleAnalytics = "G-813GH0XF8X"
disqusShortname = ""

[taxonomies]
  tag = "tags"

[author]
  name = "BG7ZDQ"

[markup.goldmark.renderer]
  unsafe = true

[params]
  math = true
  description = "Space is Closer Than You Think."
  showReadMore = true
  email = "contact@satellites.ac.cn"
  twitter = "https://twitter.com/Hyacinth_Sat"
  github = "https://github.com/HyacinthSat"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 2

[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 3

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
  [privacy.instagram]
    simple = true
  [privacy.twitter]
    simple = true
  [privacy.youtube]
    privacyEnhanced = true
